language: python
sudo: false
python:
  - "2.7"
virtualenv:
    system_site_packages: true
env:
  global:
    - secure: "L2ja+ZnV83w4qG3E8FwTjm0D6IWNOnj5wuFOjYTwbzQP4OAgLAWBzCMtxzWy5sMxFLtRgkswBH1d5f5kg8Ab7GIyAMFgQwe8UFqMJ+N05QNszE1mJkAvJtv2XN7669XXQhTt5EXfHrCcGZaODVnI2CEA8GB5DxiHO2Lcqf/xvgE="
addons:
  apt:
    packages:
    - git

before_install:
  # Set up anaconda
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  # Update conda itself
  - conda update --yes conda

install:
  # Install the RMG v0.1.0 binaries
  - conda install -c rmg -y rmg=1.0.0 rmgdatabase=1.0.0

script: 
  # Run minimal example
  - cd examples/rmg/minimal
  - rmg.py input.py
